accelerate = {
    # "Aasawari Bhagwat", Zentree
    # "Hari Sanker", Zentree,
    "Ramakrishna Gadipalli": 1922,
    "Durga  Chamada": 1434,
    "Namrata Anand": 1491,
    "Sireesha Bade": 1979,
    "Abhinav Singh": 3660,
    "Eisha Deambi": 2495,
    "Avinash Sharma": 3436,
    "Shilpa Radhakrishnan": 2926,
    "Suchitra Kona": 2935,
    "Seema Mittal": 2946,
    "Shubhala Subramanian": 3261,
    "Chidambaram Kasimuthu": 3342,
    "Madhuchetan Doddakamaiah" : 3517,
    "Pratik Namjoshi": 3021,
    "Deepak Kumar Sahu": 3027,
    "Sonam Khomane Gawade": 3083,
    "Naveen Abbigeri": 1389,
    "Ashish Narang": 'RH0242',
    "Adinarayana Reddy": 3149,
    "Nazima Begum": 3160,
    "Suda Sravanti": 3165,
    "Zubair Ahmed": 3169,
    "Kamesh Dabbara": 3190,
    "Shalu Gupta": 3172,
    "N.Bharath Kumar": 2670,
    "Mohan Babu": 3063,
    'Nithish Kumar': 1708,
    'Parth Walia': 3240,
    'Amrita Kumari': 3298,
    'Ramana Reddy': 2628,
    "Arjun BN": 2919,
    "Nitinshekar Shetty": 3334,
    "Anji Reddy": 1786,
    "Chireddy Pradeep Reddy": 3409,
    "Deepak Desai": 3449,
    "Hari Sanker": 3386,
    # "Jahnavi Pattipati": Zentree
    # "Sushuma Bandanadham" : Zentree
    "Sehjad Khan": 2436,
    "RaviKumar SM" : 3748,
    "Pranjali Awasthi" : 2620,
    "Ajith Hanagawadimath": 2646,
    "Kamal Verma": 2845,
    "Nandkishor Sahu": 2234,
    "Prakash Thombare": 3115,
}

appdev = {
    "Siva Sanker Reddy": 1961,
    "Vinod R": 2598,
    "Hemant Pasricha": 2890,
    "Kishore Babu": 2989,
    "Manojkumar Hanumanthashetty": 3000,
    "Vinaykumar Jeyaraj": 3008,
    "Sonal Saxena": 2995,
    "Jyoshna Kancham": 2645,
    "Naveen Jayam": 3271,
    "Rakesh Lenka": 3456,
    #"Narasimha Rao Mannepalli " - Contracter
    #"SaiRam Tanniru - Zentree"
    "Bikashjyoti Deka": 3693,
    "Sampad Rout": 1299,
    "Manjula MG": 3170,
    "Md. Dilshad Ahmad": 3831,
    "Koti Kajuluti": 3876,
    "Vallimaruthi Bathala": 3800,
     "Mahesh Konduru": 3023,
    "Manjula MG": 3170,

}

cod = {
    "Bhimavarapu Mohana Vyshnavi": 3074,
    "Maneesh Rao": 3311,
    "Sri Harsha Gudisa": 3817,
}

bi_team = {
    "Mithun UrsN": 3162,
    "Akanksha Namdeo": 3171,
    "Bhavesh Parekh": 3179,
    "Rajeswari Raja" : 3673,
    "Shubhala Subramanian": 3261,
}

corvesta = {"Siva Kalyan Karpurapu": 1227,
            "Rasmi Muduli": 1256,
            "Somasunder CS": 1296,
            "Lokesh Veerappa": 1519,
            "Rajesh Gopal": 1570,
            "Swami Paruchuri": 1746,
            "Venkatesh Sarvepalli": 1782,
            "Jeetendra Kumar": 1860,
            "Vibin Siby": 1887,
            "Prasad Sangodkar": 2047,
            "Ashish Jain": "RH0085",
            "Nagashruthi Karunakar": 2169,
            "Manoj Sharma": 2259,
            "Jyotirmoy Nayak": 2287,
            "Jithendra Sompalli": 2348,
            "Vijayendra Mani Rai": 2393,
            "Ramu Inturi": 2425,
            "Ushas VU": 2482,
            "G S. Kumar": 2562,
            "Eswar Adabala": 2306,
            "Pradeep Patro": 3094,
            }


cinch_details = {'Namrata Anand': {'Account': 'Accelerate', 'On-Board Date': '10/7/2019'},
                'Aasawari Bhagwat': {'Account': 'Accelerate', 'On-Board Date': '04/01/2021'},
                 'Ramakrishna Gadipalli': {'Account':'Accelerate', 'On-Board Date': '02/23/2021'},
                 'Shilpa Radhakrishnan': {'Account': 'Accelerate',
                                          'On-Board Date': '10/7/2019'},
                 'Swathi Kadoor': {'Account': 'Accelerate', 'On-Board Date': '10/7/2019'},
                 'Durga  Chamada': {'Account': 'Accelerate', 'On-Board Date': '10/10/2019'},
                 'Sireesha Bade': {'Account': 'Accelerate', 'On-Board Date': '10/19/2019'},
                 'Suchitra Kona': {'Account': 'Accelerate', 'On-Board Date': '10/14/2019'},
                 'Seema Mittal': {'Account': 'Accelerate', 'On-Board Date': '10/22/2019'},
                 #'Eisha Deambi': {'Account': 'Accelerate', 'On-Board Date': '01/22/2020'}, Shadow
                 'Pratik Namjoshi': {'Account': 'Accelerate', 'On-Board Date': '01/23/2020'},
                 'Mahesh Konduru': {'Account': 'Accelerate', 'On-Board Date': '1/28/2020'},
                 'Deepak Kumar Sahu': {'Account': 'Accelerate', 'On-Board Date': '01/29/2020'},
                 'Bhimavarapu Mohana Vyshnavi': {'Account': 'CoD',
                                                 'On-Board Date': '04/06/2020'},
                 'Mohan Babu': {'Account': 'Accelerate', 'On-Board Date': '03/10/2020'},
                 'Kishore Babu': {'Account': 'Appdev', 'On-Board Date': '12/12/2019'},
                 'Hemant Pasricha': {'Account': 'Appdev', 'On-Board Date': '12/12/2019'},
                 'Sonal Saxena': {'Account': 'Appdev', 'On-Board Date': '12/19/2019'},
                 'Vinod R': {'Account': 'Appdev', 'On-Board Date': '12/19/2019'},
                 'Manojkumar Hanumanthashetty': {'Account': 'Appdev',
                                                 'On-Board Date': '12/30/2019'},
                 'Siva Sanker Reddy': {'Account': 'Appdev', 'On-Board Date': '1/20/2020'},
                 'Vinaykumar Jeyaraj': {'Account': 'Appdev', 'On-Board Date': '1/20/2020'},
                 'Sonam Khomane Gawade': {'Account': 'Accelerate', 'On-Board Date': '04/03/2020'},
                 'Hari Sanker': {'Account': 'Accelerate', 'On-Board Date': '04/07/2020'},
                 'Naveen Abbigeri': {'Account': 'Accelerate', 'On-Board Date': '07/07/2020'},
                 'Ashish Narang': {'Account': 'Accelerate', 'On-Board Date': '06/24/2020'},
                 'Adinarayana Reddy': {'Account': 'Accelerate', 'On-Board Date': '07/07/2020'},
                 'Nazima Begum': {'Account': 'Accelerate', 'On-Board Date': '07/15/2020'},
                 'Suda Sravanti': {'Account': 'Accelerate', 'On-Board Date': '07/22/2020'},
                 'Zubair Ahmed': {'Account': 'Accelerate', 'On-Board Date': '07/22/2020'},
                 'Sampad Rout': {'Account': 'Appdev', 'On-Board Date': '07/06/2020'},
                 'Manjula MG': {'Account': 'QA Automation', 'On-Board Date': '07/22/2020'},
                 'Kamal Verma': {'Account': 'Case Management', 'On-Board Date': '06/17/2020'},
                 'Mithun UrsN': {'Account': 'BI', 'On-Board Date': '07/16/2020'},
                 'Akanksha Namdeo': {'Account': 'BI', 'On-Board Date': '07/22/2020'},
                 'Bhavesh Parekh': {'Account': 'BI', 'On-Board Date': '08/04/2020'},
                 'Nitinshekar Shetty': {'Account': 'Accelerate', 'On-Board Date': '10/21/2020'},
                 'Shalu Gupta': {'Account': 'Accelerate', 'On-Board Date': '08/10/2020'},
                 'Kamesh Dabbara': {'Account': 'Appdev', 'On-Board Date': '08/05/2020'},
                 'Ajith Hanagawadimath': {'Account': 'QA Automation', 'On-Board Date': '08/03/2020'},
                 'Jyoshna Kancham': {'Account': 'Appdev', 'On-Board Date': '08/19/2020'},
                 'Shubhala Subramanian': {'Account': 'BI', 'On-Board Date': '09/07/2020'},
                 'Nithish Kumar': {'Account': 'Case Management', 'On-Board Date': '09/30/2020'},
                 'Parth Walia': {'Account': 'Accelerate', 'On-Board Date': '09/22/2020'},
                 'Amrita Kumari': {'Account': 'Accelerate', 'On-Board Date': '09/23/2020'},
                 'Ramana Reddy': {'Account': 'Accelerate', 'On-Board Date': '09/24/2020'},
                 'Maneesh Rao': {'Account': 'CoD', 'On-Board Date': '10/01/2020'},
                 'Arjun BN': {'Account': 'Accelerate', 'On-Board Date': '10/01/2020'},
                 'Anji Reddy': {'Account': 'Accelerate', 'On-Board Date': '11/02/2020'},
                 'Chireddy Pradeep Reddy': {'Account': 'Accelerate', 'On-Board Date': '12/07/2020'},
                  'Deepak Desai': {'Account': 'Accelerate', 'On-Board Date': '12/10/2020'},
                 'Jahnavi Pattipati': {'Account': 'Accelerate', 'On-Board Date': ' 11/02/2020'},
                 'Sehjad Khan': {'Account': 'Accelerate', 'On-Board Date': ' 10/28/2020'},
                 'Avinash Nakhate': {'Account': 'Accelerate', 'On-Board Date': ' 12/12/2020'},
                 'Avinash Sharma': {'Account': 'Accelerate', 'On-Board Date': ' 12/12/2020'},
                 'Naveen Jayam': {'Account': 'Accelerate', 'On-Board Date': ' 01/07/2020'},
                 'Rajeswari Raja': {'Account': 'BI', 'On-Board Date': '04/01/2021'},
                 'Bikashjyoti Deka': {'Account': 'Appdev', 'On-Board Date': '04/01/2021'},
                 'Sai Ram Tanniru': {'Account': 'Appdev', 'On-Board Date': '03/23/2021'},
                 'Narasimha Rao Mannepalli': {'Account': 'Appdev', 'On-Board Date': '03/24/2021'},
                 #'Pranjali Awasthi': {'Account': 'Accelerate', 'On-Board Date': '03/31/2021'}, Shadow
                 'RaviKumar SM': {'Account': 'Accelerate', 'On-Board Date': '04/26/2021'},
                 'Sushuma Bandanadham': {'Account': 'Accelerate', 'On-Board Date': '03/23/2021'},
                 'Nandkishor Sahu': {'Account': 'Accelerate', 'On-Board Date': '02/09/2021'},
                 'Madhuchetan Doddakamaiah': {'Account': 'Accelerate', 'On-Board Date': '01/11/2021'},
                 'Chidambaram Kasimuthu': {'Account': 'Accelerate', 'On-Board Date': '02/01/21'},
                 'Abhinav Singh': {'Account': 'Accelerate', 'On-Board Date': '03/23/2021'},
                 'Prakash Thombare': {'Account': 'Accelerate', 'On-Board Date': '04/22/2021'},
                 'Rakesh Lenka': {'Account': 'Appdev', 'On-Board Date': '03/18/2021'},
                 'Vallimaruthi Bathala': {'Account': 'Appdev', 'On-Board Date': '05/18/2021'},
                 #'Sri Harsha Gudisa': {'Account': 'COD', 'On-Board Date': ''}, Shadow
                 }
